### ISSUE TITLE
On gesture navigation, hiding navigation bar causes glitches

### ISSUE THREAD

**Issue by kuteki707** [crdroidandroid/android_device_oneplus_instantnoodlep#1]
When using gesture navigation, if you hide the navigation bar the "back" gesture stops working. It starts working again if you disable back gesture animation. Also, incoming call screen is not displayed if the navigation bar is hidden.

**Comment by gwolf2u** [comment]
github is for source related issues
for device specific issues, do contact device maintainer via support forum or telegram if available
https://crdroid.net/instantnoodlep/7
